import type { SavedSourceDocumentRecord } from "../persistence/LocalVaultDatabase";

export type SourceCardMetadataCompletionFieldStatus =
  | "available"
  | "needs_review"
  | "not_applicable"
  | "blocked";

export interface SourceCardMetadataCompletionField {
  label: string;
  note: string;
  status: SourceCardMetadataCompletionFieldStatus;
  value: string;
}

export interface SourceCardMetadataCompletionGroup {
  fields: SourceCardMetadataCompletionField[];
  title: string;
}

export interface SourceCardMetadataCompletionFutureAction {
  disabled: true;
  label: string;
}

export interface SourceCardMetadataCompletionSafetyFlags {
  apaFinalVerified: false;
  citationMetadataInferred: false;
  metadataEditable: false;
  metadataSaved: false;
  sourceCardCreated: false;
}

export interface SourceCardMetadataCompletionPreview {
  fieldGroups: SourceCardMetadataCompletionGroup[];
  futureActions: SourceCardMetadataCompletionFutureAction[];
  safetyFlags: SourceCardMetadataCompletionSafetyFlags;
  warnings: string[];
}

const needsReviewValue = "Needs review";
const notProvidedValue = "Not provided yet";

export function createSourceCardMetadataCompletionPreview(
  detail: SavedSourceDocumentRecord
): SourceCardMetadataCompletionPreview {
  return {
    fieldGroups: [
      {
        title: "Root identity",
        fields: [
          createField(
            "SourceDocument title",
            detail.title,
            "Existing saved SourceDocument root title.",
            "blocked"
          ),
          createField(
            "File name",
            detail.fileName,
            "Existing saved SourceDocument file name.",
            "blocked"
          ),
          createField(
            "Source type / file type",
            detail.fileType,
            "Existing saved SourceDocument source type/file type.",
            "blocked"
          ),
          createField(
            "Intake candidate id / provenance",
            detail.createdFromCandidateId,
            "Existing intake provenance when available; missing provenance is not guessed.",
            "needs_review"
          )
        ]
      },
      {
        title: "Bibliographic essentials",
        fields: [
          createMissingReviewField(
            "Authors",
            "Authors are not stored on the SourceDocument root."
          ),
          createMissingReviewField(
            "Year",
            "Year/date is not stored on the SourceDocument root."
          ),
          createField(
            "Source type",
            detail.fileType,
            "Future review must confirm whether the file type is the correct bibliographic source type.",
            "blocked"
          ),
          createField(
            "Title confirmation",
            detail.title,
            "Future review must confirm this title is the correct citation title.",
            "blocked"
          )
        ]
      },
      {
        title: "Source-type-specific fields",
        fields: [
          createMissingReviewField(
            "Journal / container",
            "Journal, book, website, or report container is not inferred."
          ),
          createMissingReviewField(
            "Publisher",
            "Publisher or institution is not inferred."
          ),
          createMissingReviewField("DOI", "DOI is not looked up or inferred."),
          createMissingReviewField("URL", "URL is not looked up or inferred."),
          createMissingReviewField(
            "Volume / issue / pages",
            "Volume, issue, and page range remain source-type-specific review fields."
          )
        ]
      },
      {
        title: "Citation readiness",
        fields: [
          createMissingReviewField(
            "Citation text",
            "Citation text is not verified or generated by this preview."
          ),
          {
            label: "APA candidate",
            note: "APA candidate preview is not final and is not generated here.",
            status: "needs_review",
            value: "Not final"
          },
          {
            label: "Human review",
            note: "Human metadata review is required before any future SourceCard creation.",
            status: "needs_review",
            value: "Required"
          }
        ]
      },
      {
        title: "Future approval",
        fields: [
          {
            label: "Explicit metadata review",
            note: "Future metadata review must be explicit before any save path exists.",
            status: "needs_review",
            value: "Required"
          },
          {
            label: "Explicit SourceCard creation approval",
            note: "Future SourceCard creation must require a separate approval action.",
            status: "needs_review",
            value: "Required"
          }
        ]
      }
    ],
    futureActions: [
      {
        disabled: true,
        label: "Future: Save reviewed metadata"
      },
      {
        disabled: true,
        label: "Future: Create SourceCard after review"
      }
    ],
    safetyFlags: {
      apaFinalVerified: false,
      citationMetadataInferred: false,
      metadataEditable: false,
      metadataSaved: false,
      sourceCardCreated: false
    },
    warnings: [
      "Preview only -- metadata is not saved and no SourceCard is created.",
      "Missing bibliographic values show as Needs review or Not provided yet.",
      "Citation and APA readiness are not verified.",
      "No authors, year, DOI, journal, publisher, citation text, or APA reference is inferred."
    ]
  };
}

function createField(
  label: string,
  value: string | null | undefined,
  note: string,
  missingStatus: SourceCardMetadataCompletionFieldStatus
): SourceCardMetadataCompletionField {
  const normalizedValue = value?.trim();

  return {
    label,
    note,
    status: normalizedValue ? "available" : missingStatus,
    value: normalizedValue || (missingStatus === "blocked" ? notProvidedValue : needsReviewValue)
  };
}

function createMissingReviewField(
  label: string,
  note: string
): SourceCardMetadataCompletionField {
  return {
    label,
    note,
    status: "needs_review",
    value: needsReviewValue
  };
}
